import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col max-w-3xl mx-auto h-[100vh]">
          <Navbar />
          <div className="mt-8 grow">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
